//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fhwk.MsSql.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConventionFormats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConventionFormats() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fhwk.MsSql.Resources.ConventionFormats", typeof(ConventionFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PK__{0}.
        /// </summary>
        public static string PrimaryKeyTable {
            get {
                return ResourceManager.GetString("PrimaryKeyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PK__{0}__{1}.
        /// </summary>
        public static string PrimaryKeyTableColumn {
            get {
                return ResourceManager.GetString("PrimaryKeyTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}__{1}__PK.
        /// </summary>
        public static string PrimaryKeyTableColumnSuffix {
            get {
                return ResourceManager.GetString("PrimaryKeyTableColumnSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}__PK.
        /// </summary>
        public static string PrimaryKeyTableSuffix {
            get {
                return ResourceManager.GetString("PrimaryKeyTableSuffix", resourceCulture);
            }
        }
    }
}
