//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fhwk.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConventionFormats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConventionFormats() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fhwk.Core.Resources.ConventionFormats", typeof(ConventionFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        internal static string ColumnNameSeparator {
            get {
                return ResourceManager.GetString("ColumnNameSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string DefaultForeignKeyColumnSuffix {
            get {
                return ResourceManager.GetString("DefaultForeignKeyColumnSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdKey.
        /// </summary>
        internal static string ElementKeyColumnName {
            get {
                return ResourceManager.GetString("ElementKeyColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ElementValueColumnName {
            get {
                return ResourceManager.GetString("ElementValueColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK__{0}__{1}.
        /// </summary>
        internal static string ForeignKeySourceTarget {
            get {
                return ResourceManager.GetString("ForeignKeySourceTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK__{0}__{1}__{2}.
        /// </summary>
        internal static string ForeignKeySourceTargetKey {
            get {
                return ResourceManager.GetString("ForeignKeySourceTargetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}__{1}__{2}__FK.
        /// </summary>
        internal static string ForeignKeySourceTargetKeySuffix {
            get {
                return ResourceManager.GetString("ForeignKeySourceTargetKeySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}__{1}__FK.
        /// </summary>
        internal static string ForeignKeySourceTargetSuffix {
            get {
                return ResourceManager.GetString("ForeignKeySourceTargetSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.
        /// </summary>
        internal static string ManyToManyNoSeparator {
            get {
                return ResourceManager.GetString("ManyToManyNoSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}To{1}.
        /// </summary>
        internal static string ManyToManyToSeparator {
            get {
                return ResourceManager.GetString("ManyToManyToSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_{1}.
        /// </summary>
        internal static string ManyToManyUndescoreSeparator {
            get {
                return ResourceManager.GetString("ManyToManyUndescoreSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_{1}.
        /// </summary>
        internal static string RelationshipUnderscoreSeparated {
            get {
                return ResourceManager.GetString("RelationshipUnderscoreSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_s.
        /// </summary>
        internal static string SourceColumnName {
            get {
                return ResourceManager.GetString("SourceColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_t.
        /// </summary>
        internal static string TargetColumnName {
            get {
                return ResourceManager.GetString("TargetColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_.
        /// </summary>
        internal static string UnderscoreSuffix {
            get {
                return ResourceManager.GetString("UnderscoreSuffix", resourceCulture);
            }
        }
    }
}
